### ISSUE TITLE
Doesn't get along with Ember Inspector

### ISSUE THREAD

**Issue by amedrz** [ahmadsoe/ember-offline#1]
```
Chrome 44.0.2403.125
Ember Inspector 1.8.3
Ember 1.13.5
Ember Data 1.13.7
```

I'm getting this on the console only when I try to load the deprecations tab of Ember Inspector which then doesn't work.

```
Uncaught TypeError: Cannot read property 'responseText' of null
  RSVP.Promise.xhr.onload @ VM1710:1460
  a.onprogress.a.onload @ offline.min.js:1
```

After uninstalling `ember-offline` everything worked just fine.

Thanks

**Comment by ahmadsoe** [comment]
@amedrz Thanks for opening issue. I am not yet sure what's causing this.
From the error message, it seems that you have problems with your ajax response.

can you provide a public repo to reproduce this?

**Comment by diamond-darrell** [comment]
Have got same error, but I use offline.js without addon, seems that is related only to ember-inspector and offline.js

**Comment by ahmadsoe** [comment]
@amedrz feel free to reopen the issue if you still seeing this error.
